spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/spike?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            username: DinoStark
            password: non-feeling
    redis:
        host: localhost
        port: 6379

dataworks:
    easy-minio:
        endpoint: http://localhost:9000
        access-key: minioadmin
        secret-key: minioadmin
