spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/spike?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
            username: DinoStark
            password: non-feeling
    redis:
        host: localhost
        port: 6379
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848

dubbo:
    application:
        name: ${spring.application.name}-dubbo
    registry:
        address: nacos://${spring.cloud.nacos.discovery.server-addr}
    protocol:
        name: dubbo
        port: -1
